name: CI/CD

on:
  push:
    branches:
    - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose --release
